import React, { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';
import api from '../api/axios';
import { analyzeMenuBudget, MENU_PRICE_LIMIT_DH } from '../utils/menuPrices';

const DashboardContext = createContext(null);

// Local storage for notifications removed in favor of DB


function loadSysConfig() {
  try {
    const raw = localStorage.getItem('sysConfig');
    return raw ? JSON.parse(raw) : { theme: 'light', language: 'fr', itemsPerPage: 10 };
  } catch {
    return { theme: 'light', language: 'fr', itemsPerPage: 10 };
  }
}

export function DashboardProvider({ children, onNavigate }) {
  const [notifications, setNotifications] = useState([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [searchResults, setSearchResults] = useState([]);
  const [searchLoading, setSearchLoading] = useState(false);
  const [showNotifications, setShowNotifications] = useState(false);
  const [showSearchResults, setShowSearchResults] = useState(false);
  const [sysConfig, setSysConfigState] = useState(loadSysConfig);

  const setSysConfig = useCallback((updated) => {
    const next = typeof updated === 'function' ? updated(sysConfig) : updated;
    setSysConfigState(next);
    localStorage.setItem('sysConfig', JSON.stringify(next));
  }, [sysConfig]);

  // Fetch notifications from API
  const fetchNotifications = useCallback(async () => {
    try {
      const res = await api.get('/notifications');
      setNotifications(res.data);
    } catch (err) {
      console.error('Erreur lors du chargement des notifications:', err);
    }
  }, []);

  useEffect(() => {
    fetchNotifications();
    // Set up polling every minute to fetch new notifications
    const interval = setInterval(fetchNotifications, 60000);
    return () => clearInterval(interval);
  }, [fetchNotifications]);

  const unreadCount = useMemo(
    () => notifications.filter((n) => !n.read).length,
    [notifications]
  );

  const addNotification = useCallback((notification) => {
    // Keep this for frontend-only temporary alerts if needed, 
    // but the main alerts are now generated by the backend.
    const entry = {
      id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      read: false,
      created_at: new Date().toISOString(),
      type: 'info',
      ...notification,
    };
    setNotifications((prev) => {
      const exists = prev.some(
        (n) => n.title === notification.title && n.message === notification.message
      );
      if (exists) return prev;
      return [entry, ...prev].slice(0, 50);
    });
    return entry;
  }, []);

  const markNotificationRead = useCallback(async (id) => {
    try {
      await api.put(`/notifications/${id}/read`);
      setNotifications((prev) =>
        prev.map((n) => (n.id === id ? { ...n, read: true } : n))
      );
    } catch (err) {
      console.error('Error marking notification as read', err);
    }
  }, []);

  const markAllNotificationsRead = useCallback(async () => {
    try {
      await api.put('/notifications/read-all');
      setNotifications((prev) => prev.map((n) => ({ ...n, read: true })));
    } catch (err) {
      console.error('Error marking all notifications as read', err);
    }
  }, []);

  const deleteNotification = useCallback(async (id) => {
    try {
      await api.delete(`/notifications/${id}`);
      setNotifications((prev) => prev.filter((n) => n.id !== id));
    } catch (err) {
      console.error('Error deleting notification', err);
    }
  }, []);



  useEffect(() => {
    if (searchQuery.trim().length < 2) {
      setSearchResults([]);
      setSearchLoading(false);
      return undefined;
    }

    setSearchLoading(true);
    const timer = setTimeout(async () => {
      try {
        const res = await api.get('/search', { params: { q: searchQuery.trim() } });
        setSearchResults(res.data);
      } catch (err) {
        console.error('Erreur recherche:', err);
        setSearchResults([]);
      } finally {
        setSearchLoading(false);
      }
    }, 280);

    return () => clearTimeout(timer);
  }, [searchQuery]);

  const handleSearchSelect = useCallback(
    (result) => {
      if (onNavigate && result.tab) {
        onNavigate(result.tab, result);
      }
      setSearchQuery('');
      setSearchResults([]);
      setShowSearchResults(false);
    },
    [onNavigate]
  );

  const value = useMemo(
    () => ({
      notifications,
      unreadCount,
      addNotification,
      markNotificationRead,
      markAllNotificationsRead,
      deleteNotification,
      fetchNotifications,
      searchQuery,
      setSearchQuery,
      searchResults,
      searchLoading,
      showNotifications,
      setShowNotifications,
      showSearchResults,
      setShowSearchResults,
      handleSearchSelect,
      sysConfig,
      setSysConfig,
    }),
    [
      notifications,
      unreadCount,
      addNotification,
      markNotificationRead,
      markAllNotificationsRead,
      deleteNotification,
      fetchNotifications,
      searchQuery,
      searchResults,
      searchLoading,
      showNotifications,
      showSearchResults,
      handleSearchSelect,
      sysConfig,
      setSysConfig,
    ]
  );

  return (
    <DashboardContext.Provider value={value}>{children}</DashboardContext.Provider>
  );
}

export function useDashboard() {
  const ctx = useContext(DashboardContext);
  if (!ctx) {
    throw new Error('useDashboard must be used within DashboardProvider');
  }
  return ctx;
}
